### ISSUE TITLE
Issue in executing file Pipeline.ipynb

### ISSUE THREAD

**Issue by Aaqib-AI-TECH** [Yasir-ali-farrukh/Payload-Byte#2]
Dear Yasir, 

I hope you are doing well. 
I have three questions regarding the Payload-Byte Tool simulation. 
I downloaded the CSV files (data) from the following link;

https://cloudstor.aarnet.edu.au/plus/index.php/s/2DhnLGDdEECo4ys?path=%2FUNSW-NB15%20-%20CSV%20Files

1. Is this the correct link for the data sets? 
2. From where we can download the features.csv file?  
3. I used the above link for the datasets while executing the main file named  "Pipeline. ipynb" and faced the following error.  
Please find the attached error file. 
Your response will be highly appreciated.

**Comment by tinamil** [comment]
@Aaqi123 

I'm not Yasir but I've used Payload-Byte and helped solve some of the other issues with it.

1. Yes for the UNSW dataset. 
2. The features file is in that link named NUSW-NB15_features.csv
3. I don't see any attached error file.

**Comment by Aaqib-AI-TECH** [comment]
> @Aaqi123
> 
> I'm not Yasir but I've used Payload-Byte and helped solve some of the other issues with it.
> 
> 1. Yes for the UNSW dataset.
> 2. The features file is in that link named NUSW-NB15_features.csv
> 3. I don't see any attached error file.

**Comment by Aaqib-AI-TECH** [comment]
@tinamil  
Thank you for your feedback, here is the file 
![error_payload-byte](https://user-images.githubusercontent.com/114743568/211840066-0bf2dbdf-cfdf-4052-91b0-8994a7d59a24.png)
![error_payload-byte](https://user-images.githubusercontent.com/114743568/211840208-86f950a1-5a8e-44de-a22b-9881e297b4bf.png)

**Comment by tinamil** [comment]
@Aaqi123 The 1.0 release is somewhat out of date, which it looks like you are using. I suggest downloading the latest version of the main branch and seeing if that works better for you.
