### ISSUE TITLE
Can not get the correct labelled_pcap_csv_1.csv

### ISSUE THREAD

**Issue by manwu1994** [Yasir-ali-farrukh/Payload-Byte#3]
Hello,

Thank you for your work. I followed your code, and the code successfully ran. However, I noticed that there are empty fields in the labelled_pcap_csv_1.csv file. Do you have any idea what could be causing this issue? Thank you so much in advance for your help.

**Comment by Yasir-ali-farrukh** [comment]
Hey, Thank you.

Make sure you followed the pre-processing of the CSV file (flow data) and
you are using the latest version of the main branch.
