### ISSUE TITLE
CSV File Creation

### ISSUE THREAD

**Issue by jdellag** [Yasir-ali-farrukh/Payload-Byte#4]
Hi,

I can successfully run the UNSW example, but when trying to adjust this for my own dataset I am lost on how to create my own CSV files and the feature extraction for the preprocessing step. This may be auxiliary to using this program, but I am not quite sure; I would appreciate any feedback.

**Comment by tinamil** [comment]
Payload-Byte is very specific to running on CIC-IDS 2017 and UNSW NB-15. You'll either have to make your inputs look exactly like UNSW NB-15 or go through the code line-by-line and rewrite it to match your own dataset. I would recommend rewriting the code so that you understand what it's doing.
