### ISSUE TITLE
Mapping payload data into preprocessed data

### ISSUE THREAD

**Issue by ichsancomp** [Yasir-ali-farrukh/Payload-Byte#5]
Hello,

I appreciate all of your hard work. Your code worked for me when I followed it (Pipeline.ipynb), the output is UNSW_converted_data.csv. How we can process UNSW_converted_data.csv to be UNSW-NB15_preprocessed.csv ?

Many thanks for your assistance in advance.

**Comment by Yasir-ali-farrukh** [comment]
Thank you, The `UNSW-NB15_preprocessed.csv` file is the output of the initial step, which involves [CSV_data_preprocessing](https://github.com/Yasir-ali-farrukh/Payload-Byte/tree/main/CSV_data_preprocessing). This step includes basic preprocessing tasks, such as addressing data discrepancies and formalizing the data before it is fed into the pipeline.

To proceed, you should first preprocess the UNSW data using the [CSV_data_preprocessing](https://github.com/Yasir-ali-farrukh/Payload-Byte/tree/main/CSV_data_preprocessing) and then apply the pipeline to generate the `UNSW_converted_data.csv` file

I hope this clarifies your question.

**Comment by ichsancomp** [comment]
Thank you for your response.
According to [CSV_data_preprocessing](https://github.com/Yasir-ali-farrukh/Payload-Byte/tree/main/CSV_data_preprocessing), the input is UNSW-NB15_{i}.csv, from where we can get that file?
how we can mapping from Payload_data_UNSW.csv (containing 1500 features)?

Thank you.

**Comment by Yasir-ali-farrukh** [comment]
You can download the pcap as well as UNSW-NB15_{i}.csv from their official website: https://research.unsw.edu.au/projects/unsw-nb15-dataset.

UNSW_converted_data.csv is same as Payload_data_UNSW.csv. The file is being renamed.

**Comment by ichsancomp** [comment]
How we can process from pcap file to be UNSW-NB15_{i}.csv?
I'm sorry for your inconvenience

**Comment by Yasir-ali-farrukh** [comment]
The dataset Owner's have created flow features (UNSW-NB15_{i}.csv) by using The Argus and Bro-IDS tools. The Payload-Byte tool is labelling the individual packet as per the generated flows, furthermore it is extracting the payload information from the packets to be utilized in training machine learning models.

**Comment by ichsancomp** [comment]
Got it, thank you for your explanation.

**Comment by ichsancomp** [comment]
> The dataset Owner's have created flow features (UNSW-NB15_{i}.csv) by using The Argus and Bro-IDS tools. The Payload-Byte tool is labelling the individual packet as per the generated flows, furthermore it is extracting the payload information from the packets to be utilized in training machine learning models.

how we can capture the packet as well as UNSW-NB15 feature (45 features)?

**Comment by Yasir-ali-farrukh** [comment]
You will have to edit the code for that, so that it retain the 45 flow features too.
